apiVersion: apps/v1
kind: Deployment
metadata: 
  name: Netflix_dep
spec:
  template:
    metadata:
      name: netflixpod
      labels:
        app: netflixpod
    spec:
      containers:
      - name: netflix
        image:  kesav38/netflix:Newtag
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10 

---
apiVersion: v1 
kind: Service
metadata:
  name: netflixsvc
spec:
  type: LoadBalancer
  selector:
    app: netflixpod
  ports:
  - port: 80
    targetPort: 80
